
server:
  port: 6677
  servlet:
    context path: "/doctor-appointment/v1"

spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher

  data:
  mongodb:
    user: admin
    password: admin
    database: doctor-appointment
    uri: mongodb://localhost:27017

app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.appointment.management.ManagementApplication
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true